# Generated by Django 4.2.6 on 2023-10-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='author',
            new_name='player',
        ),
    ]
